### ISSUE TITLE
Wrong response URL

### ISSUE THREAD

**Issue by soupette** [kayvanbree/strapi-editorjs#10]
I have made a small mistake when retrieving the uploaded file url.

[This line](https://github.com/kayvanbree/strapi-editorjs/blob/358db311aa5dceb18df853e49908c57d9d65cdbe/admin/src/components/EditorJs/index.js#L104-L106)

Needs to be changed to 

```
file: {
  url: `${strapi.backendURL}${resp[0].url}`,
}
``` 
In order to remove the added `/`

cc/ @kayvanbree

**Comment by kayvanbree** [comment]
Thanks, #11 addresses this, but I'm not sure about the removal of the authorization headers in the PR

**Comment by soupette** [comment]
@kayvanbree you can remove since you are now using the request from the `strapi-helper-plugin` instead of the native one
